-- Tabela de Gastos para o MyFinances
-- Versão modificada para refletir a estrutura de dados do extrato de forma mais granular.

CREATE TABLE IF NOT EXISTS public.gastos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL,
    entrada_saida TEXT NOT NULL,
    tipo TEXT NOT NULL,
    detalhes TEXT NOT NULL,
    valor NUMERIC NOT NULL,
    categoria TEXT NOT NULL,
    descricao TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- (Opcional) Atualização do índice para acelerar a busca por itens duplicados.
-- Se a tabela já existir, talvez seja necessário remover o índice antigo primeiro:
-- DROP INDEX IF EXISTS public.idx_gastos_dedup;
CREATE INDEX IF NOT EXISTS idx_gastos_dedup_v2 ON public.gastos (data, valor, tipo, detalhes);
